version: '2'
services:
  notebook:
    build: .
    restart: always
    env_file: .env
    working_dir: "${ABSOLUTE_BASE_DIR}"
    ports:
      - "${PORT_HOST}:${PORT_CNTR}"
    volumes:
      - "${ABSOLUTE_BASE_DIR}:${ABSOLUTE_BASE_DIR}"
    environment:
      GIT_REMOTE_URL: "git@github.com:${GIT_USER}/${GIT_REPO_NAME}.git"
      GIT_REMOTE_URL_HTTPS: "https://github.com/${GIT_USER}/${GIT_REPO_NAME}.git"
      GIT_REMOTE_UPSTREAM: "${GIT_USER_UPSTREAM}/${GIT_REPO_NAME}"
